// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5wCHqbypMGZkHg8jV6b5acXIRg8MO9P4',
    appId: '1:242990178278:web:62575a9c979c72fc9f0027',
    messagingSenderId: '242990178278',
    projectId: 'flutter-firebase-1-77673',
    authDomain: 'flutter-firebase-1-77673.firebaseapp.com',
    storageBucket: 'flutter-firebase-1-77673.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUR0iqs4KnihWQ5jlBbIWEV95J1UZXY78',
    appId: '1:242990178278:android:0eb8c27866be0e4f9f0027',
    messagingSenderId: '242990178278',
    projectId: 'flutter-firebase-1-77673',
    storageBucket: 'flutter-firebase-1-77673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuJVZjwukTDwduOn-Rtm3ZkniFSHYkrZ0',
    appId: '1:242990178278:ios:aa2c20ee510e6b189f0027',
    messagingSenderId: '242990178278',
    projectId: 'flutter-firebase-1-77673',
    storageBucket: 'flutter-firebase-1-77673.appspot.com',
    iosClientId: '242990178278-mc4idag414m5fncjd7tll5kr90nfopsg.apps.googleusercontent.com',
    iosBundleId: 'no',
  );
}
